name: xekomanagermain
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.7.2
  firebase_database: ^10.1.1
  firebase_storage: ^11.1.1
  fluttertoast: ^8.2.1
  image_picker: ^1.0.4
  image: ^4.1.3
  auto_size_text: ^3.0.0
  webview_flutter: ^4.2.0
  url_launcher: ^6.1.10
  responsive_builder: ^0.6.4
  google_nav_bar: ^5.0.6
  pinput: ^2.2.31
  flutter_polyline_points: ^1.0.0
  http:
  uuid: ^3.0.7
  flutter_svg: ^2.0.5
  google_maps_flutter: ^2.3.0
  geocoding: ^2.1.0
  flutter_typeahead: ^4.6.2
  provider: ^6.0.5
  dio: ^5.2.1+1
  image_picker_web: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/mainLogo.png
    - assets/image/iconbag.png
    - assets/image/icondelivery.png
    - assets/image/iconfood.png
    - assets/image/icongift.png
    - assets/image/iconmart.png
    - assets/image/iconoffer.png
    - assets/image/icontransport.png
    - assets/image/iconbike.png
    - assets/image/iconlocation.png
    - assets/image/linhtinh1.png
    - assets/image/linhtinh2.png
    - assets/image/linhtinh3.png
    - assets/image/linhtinh4.png
    - assets/image/linhtinh5.png
    - assets/image/linhtinh6.png
    - assets/image/pickicon.png
    - assets/image/backicon.png
    - assets/image/backicon1.png
    - assets/image/bluecircle.png
    - assets/image/locationRounditem.png
    - assets/image/rightarrow.png
    - assets/image/bikeLogo1.png
    - assets/image/carLogo1.png
    - assets/image/realmoneyicon.png
    - assets/image/parcel.png
    - assets/image/iconorder.png
    - assets/image/carticon.png
    - assets/image/stick.png
    - assets/image/bgfood1.png
    - assets/image/bgfood2.png
    - assets/image/bgfood3.png
    - assets/image/garbageicon.png
    - assets/image/righticon.png
    - assets/image/icontrangchinh/iconads.png
    - assets/image/icontrangchinh/iconarea.png
    - assets/image/icontrangchinh/iconcustommer.png
    - assets/image/icontrangchinh/iconmarket.png
    - assets/image/icontrangchinh/iconorder.png
    - assets/image/icontrangchinh/iconrestaurant.png
    - assets/image/icontrangchinh/iconshipper.png
    - assets/image/icontrangchinh/iconvoucher.png
    - assets/image/icontrangchinh/iconnotice.png
    - assets/image/redcircle.png
    - assets/image/greycircle.png
    - assets/image/orangecircle.png

  fonts:
    - family: logo_font_1
      fonts:
        - asset: assets/font/logofont1.otf

    - family: Dmsan_regular
      fonts:
        - asset: assets/font/DMSans_regu.ttf


    - family: arial
      fonts:
        - asset: assets/font/arial.TTF


    - family: timenew
      fonts:
        - asset: assets/font/times.ttf

    - family: roboto
      fonts:
        - asset: assets/font/Roboto.ttf
